version: '2'
services:
    consul-server:
      container_name: consul-server-f22
      image: consul
      ports:
       - "8500:8500" # Needed to expose to host.
      expose: # Needed to expose ports to linked containers
       - "443"
       - "8300-8600" # Used for speed of development. In future reduce to only necessary ports.
      environment: 
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}' # Used when only 1 in cluster.
      networks:
        - app_net # Specify IP?
      command:
       - agent 
       - -server
       - -bootstrap # Used when the first
       - -ui # Web ui
       - -client=0.0.0.0 # Ensures that all ports exposed inside container on localhost are shared with all other IPs inside container.
       - -recursor=8.8.8.8 # Secondary DNS when can't resolve locally. This is Google's DNS.
    registrator:
      container_name: registrator-f22
      image: gliderlabs/registrator:latest
      networks:
        - app_net
      volumes: 
        - /var/run/docker.sock:/tmp/docker.sock
      depends_on: 
        - consul-server
      links:
        - consul-server
      dns: 
       - consul-server
       - 8.8.8.8 # When it can't resolve an IP it will use Googles DNS
      dns_search: service.consul
      command:
       - consul://consul-server:8500
    nginx: 
      build: ../../nginx # Assumes Dockerfile
      container_name: nginx-f22
      image: nginx-f22
      networks:
        - app_net
      volumes: 
       - ${NGINX_SHARED_DIR}:/usr/share/nginx/
      ports:
        - "80:80"
        - "82:82"
      links:
        - consul-server
        - webapp
      dns: 
        - consul-server
        - 8.8.8.8
      dns_search: service.consul
      entrypoint: nginx
      command: 
        - -g
        - "daemon off;"
        - -c
        - /usr/share/nginx/conf/nginx.conf
    webapp:
      build: 
        context: /home/f22/loading-dock/staging/fletch22Website
        args:
        - NEXUS_URI=$NEXUS_URI
      container_name: webapp-f22
      image: webapp-f22
      networks:
       - app_net
      mem_limit: 2000000000
      expose:
       - "8888"
      ports: 
       - "58888:8888"
      depends_on:
       - registrator
      dns: 
       - consul-server
       - 8.8.8.8
      dns_search: service.consul    
networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1